version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - db-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "select 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: /bin/bash -c '(/opt/mssql/bin/sqlservr & ) && sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q "CREATE DATABASE SalesAndInventoryTest;"'

volumes:
  db-data:
